database:
  image: admin.datapunt.amsterdam.nl:5000/atlas/postgres
  ports:
    - "5401:5432"
  environment:
    POSTGRES_DB: bgt
    POSTGRES_USER: bgt
    POSTGRES_PASSWORD: insecure

# TODO: Perhaps volume is not needed? Download and import within docker
importer:
  build: .
  links:
    - database:database
  volumes:
    - /tmp/bgt:/tmp/bgt
  environment:
    DB_NAME: bgt
    DB_USER: bgt
    DB_PASSWORD: insecure
  command: >
    bash -c "/app/docker-wait.sh \
            && /app/import_bgt.sh"
