version: "2.1"
services:
  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    ports:
      - "5401:5432"
    environment:
      POSTGRES_DB: gisdb
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: insecure

  importer:
    build: .
    links:
      - database:database
    environment:
      FMESERVER:
      FMESERVERAPI:
      FMEAPI:
      FMEDBPASS:
      FMEINSTANCE:
      DEBUG:
      OBJECTSTORE_PASSWORD:
    volumes:
      - /tmp/data:/tmp/data
    command: >
      bash -c "/app/docker-wait_fme.sh \
              && /app/import_fme.sh"
