database:
  image: admin.datapunt.amsterdam.nl:5000/atlas/postgres
  ports:
    - "5401:5432"
  environment:
    POSTGRES_DB: bgt
    POSTGRES_USER: bgt
    POSTGRES_PASSWORD: insecure

importer:
  build: .
  links:
    - database:database
  environment:
    DB_NAME: bgt
    DB_USER: bgt
    DB_PASSWORD: insecure
  env_file: keys.env
  command: >
    bash -c "/app/docker-wait.sh \
            && /app/import_bgt.sh"
