database_TMP:
  image: admin.datapunt.amsterdam.nl:5000/atlas/postgres
  environment:
    POSTGRES_USER: dbuser
    POSTGRES_PASSWORD: insecure

database_BGT:
  image: admin.datapunt.amsterdam.nl:5000/atlas/postgres
  environment:
    POSTGRES_USER: dbuser
    POSTGRES_PASSWORD: insecure

tests:
  build: ..
  links:
    - database_TMP:database_TMP
    - database_BGT:database_BGT
  environment:
    POSTGRES_DB: bgt
    POSTGRES_USER: bgt
    POSTGRES_PASSWORD: insecure
    OBJECTSTORE_PASSWORD:

  command: >
    bash -c "cd /src && \
            pip install -r requirements.txt \
            && export TEST=1 && python py.test"

importer:
  build: ..
  links:
    - database_TMP:database_TMP
    - database_BGT:database_BGT
  environment:
    DB_NAME: bgt
    DB_USER: bgt
    DB_PASSWORD: insecure
    FMEAPI:
  command: >
    bash -c "/docker/docker-wait.sh \
            && /app/import_bgt.sh"

db-backup:
  image: admin.datapunt.amsterdam.nl:5000/atlas/postgres
  links:
    - database_TMP:db1
    - database_BGT:db2
  volumes:
    - ./backups:/tmp/backups
  command: >
    bash -c "echo db:5432:bgt:bgt:insecure > ~/.pgpass \
            && chmod 600 ~/.pgpass \
            && pg_dump --clean \
                        -Fc \
                        -U bgt \
                        -h db1 -p 5432 \
                        bgt > /tmp/backups/database_tmp.dump \
            && pg_dump --clean \
                        -Fc \
                        -U bgt \
                        -h db2 -p 5432 \
                        bgt > /tmp/backups/database_bgt.dump"
                        "
