version: "2.1"
services:
  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    environment:
      POSTGRES_DB: gisdb
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: insecure

  tests:
   build: ..
   links:
     - database:database
   command: >
     bash -c "/app/docker-wait_bgt.sh \
             && /app/docker-wait_fme.sh \
             && cd /src \
             && pip install -r requirements.txt \
             && export TEST=1 \
             && py.test /src"

  importer:
    build: ..
    links:
      - database:database
    environment:
      FMESERVER: ${FMESERVER}
      FMESERVERAPI: ${FMESERVERAPI}
      FMEAPI: ${FMEAPI}
      FMEDBPASS: ${FMEDBPASS:-insecure}
      FMEINSTANCE: ${FMEINSTANCE:-2493}
      DEBUG: ${DEBUG:-0}
      BGT_OBJECTSTORE_PASSWORD: ${BGT_OBJECTSTORE_PASSWORD:-insecure}
    volumes:
      - /tmp/data:/tmp/data
    command: >
      bash -c "/app/docker-wait.sh \
              && /app/import_fme.sh"

