database_FME:
  image: build.datapunt.amsterdam.nl:5000/atlas/postgres
  environment:
    POSTGRES_DB: gisdb
    POSTGRES_USER: dbuser
    POSTGRES_PASSWORD: insecure


database_BGT:
  image: build.datapunt.amsterdam.nl:5000/atlas/postgres
  environment:
    POSTGRES_DB: bgt
    POSTGRES_USER: bgt
    POSTGRES_PASSWORD: insecure


tests:
  build: ..
  links:
    - database_FME:database_FME
    - database_BGT:database_BGT
  command: >
    bash -c "/app/docker-wait_bgt.sh \
            && /app/docker-wait_fme.sh \
            && cd /src \
            && pip install -r requirements.txt \
            && export TEST=1 \
            && py.test /src"


importer_fme:
  build: ..
  links:
    - database_FME:database_FME
  volumes:
    - /tmp/data:/tmp/data
  command: >
    bash -c "/app/docker-wait_fme.sh \
            && /app/import_fme.sh"


importer_bgt:
  build: ..
  links:
    - database_BGT:database_BGT
  volumes:
    - /tmp/data:/tmp/data
  command: >
    bash -c "/app/docker-wait_bgt.sh \
            && /app/import_bgt.sh"


db-backup_bgt:
  image: build.datapunt.amsterdam.nl:5000/atlas/postgres
  links:
    - database_BGT:db2
  volumes:
    - ./backups:/tmp/backups
  command: >
    bash -c "echo db:5432:bgt:bgt:insecure > ~/.pgpass \
            && chmod 600 ~/.pgpass \
            && pg_dump --clean \
                        -Fc \
                        -U bgt \
                        -h db2 -p 5432 \
                        bgt > /tmp/backups/database.dump
                        "
