database:
  image: admin.datapunt.amsterdam.nl:5000/atlas/postgres
  environment:
    POSTGRES_DB: bgt
    POSTGRES_USER: bgt
    POSTGRES_PASSWORD: insecure

importer:
  build: ..
  links:
    - database:database
  environment:
    DB_NAME: bgt
    DB_USER: bgt
    DB_PASSWORD: insecure
  command: >
    bash -c "/docker/docker-wait.sh \
            && /app/import_bgt.sh"

db-backup:
  image: admin.datapunt.amsterdam.nl:5000/atlas/postgres
  links:
    - database:db
  volumes:
    - ./backups:/tmp/backups
  command: >
    bash -c "echo db:5432:bgt:bgt:insecure > ~/.pgpass \
            && chmod 600 ~/.pgpass \
            && pg_dump --clean \
                        -Fc \
                        -U bgt \
                        -h db -p 5432 \
                        bgt > /tmp/backups/database.dump"
