version: "2.1"
services:
  importer:
    build: ..
    environment:
      FMESERVER: ${FMESERVER}
      FMESERVERAPI: ${FMESERVERAPI}
      FMEAPI: ${FMEAPI}
      FMEDBPASS: ${FMEDBPASS:-insecure}
      FMEINSTANCE: ${FMEINSTANCE:-2493}
      DEBUG: ${DEBUG:-0}
      BGT_OBJECTSTORE_PASSWORD: ${BGT_OBJECTSTORE_PASSWORD:-insecure}
      FME_TEST_RUN: ${FME_TEST_RUN:-0}
    #volumes:
    #  - /tmp/data:/tmp/data
    command: >
      bash -c "/bgt/import_fme.sh"
