database_BGT1:
  image: build.datapunt.amsterdam.nl:5000/atlas/postgres
  environment:
    POSTGRES_DB: gisdb
    POSTGRES_USER: dbuser
    POSTGRES_PASSWORD: insecure

database_BGT2:
  image: build.datapunt.amsterdam.nl:5000/atlas/postgres
  environment:
    POSTGRES_DB: bgt
    POSTGRES_USER: bgt
    POSTGRES_PASSWORD: insecure

tests:
  build: ..
  links:
    - database_BGT1:database_BGT1
    - database_BGT2:database_BGT2
  command: >
    bash -c "/app/docker-wait.sh \
            && cd /src \
            && pip install -r requirements.txt \
            && export TEST=1 \
            && python -m pytest"

importer:
  build: ..
  links:
    - database_BGT1:database_BGT1
    - database_BGT2:database_BGT2
  volumes:
    - /tmp/data:/tmp/data
  command: >
    bash -c "/app/docker-wait.sh \
            && /app/import_bgt1.sh
            && /app/import_bgt2.sh"

db-backup:
  image: build.datapunt.amsterdam.nl:5000/atlas/postgres
  links:
    - database_BGT1:db1
    - database_BGT2:db2
  volumes:
    - ./backups:/tmp/backups
  command: >
    bash -c "echo db:5432:bgt:bgt:insecure > ~/.pgpass \
            && chmod 600 ~/.pgpass \
            && pg_dump --clean \
                        -Fc \
                        -U bgt \
                        -h db1 -p 5432 \
                        bgt > /tmp/backups/database_bgt1.dump \
            && pg_dump --clean \
                        -Fc \
                        -U bgt \
                        -h db2 -p 5432 \
                        bgt > /tmp/backups/database_bgt2.dump
                        "
