\i create_vw_bgt_begroeidterreindeel.sql
\i create_vw_bgt_kruinlijn.sql
\i create_vw_bgt_nummeraanduidingreeks.sql
\i create_vw_bgt_onbegroeidterreindeel.sql
\i create_vw_bgt_ondersteunendwaterdeel.sql
\i create_vw_bgt_ondersteunendwegdeel.sql
\i create_vw_bgt_ongeclassificeerdobject.sql
\i create_vw_bgt_openbareruimtelabel.sql
\i create_vw_bgt_overbruggingsdeel.sql
\i create_vw_bgt_pand.sql
\i create_vw_bgt_plaatsbepalingspunt.sql
\i create_vw_bgt_tunneldeel.sql
\i create_vw_bgt_waterdeel.sql
\i create_vw_bgt_wegdeel.sql
\i create_vw_imgeo_bak.sql
\i create_vw_imgeo_bord.sql
\i create_vw_imgeo_functioneelgebied.sql
\i create_vw_imgeo_gebouwinstallatie.sql
\i create_vw_imgeo_installatie.sql
\i create_vw_imgeo_kast.sql
\i create_vw_imgeo_kunstwerkdeel.sql
\i create_vw_imgeo_mast.sql
\i create_vw_imgeo_overigbouwwerk.sql
\i create_vw_imgeo_overigescheiding.sql
\i create_vw_imgeo_paal.sql
\i create_vw_imgeo_put.sql
\i create_vw_imgeo_scheiding.sql
\i create_vw_imgeo_sensor.sql
\i create_vw_imgeo_spoor.sql
\i create_vw_imgeo_straatmeubilair.sql
\i create_vw_imgeo_vegetatieobject.sql
\i create_vw_imgeo_waterinrichtingselement.sql
\i create_vw_imgeo_weginrichtingselement.sql